/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TestCheckbox {
        /**
          * The active checked state
         */
        "checked"?: boolean;
        /**
          * The default checked state
         */
        "defaultChecked"?: boolean;
        /**
          * Disabled state of checkbox
         */
        "disabled"?: boolean;
        /**
          * Name of the field
         */
        "label"?: string;
        /**
          * Label associated with the field
         */
        "name": string;
        /**
          * underlying input value
         */
        "value"?: string;
    }
}
export interface TestCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTestCheckboxElement;
}
declare global {
    interface HTMLTestCheckboxElement extends Components.TestCheckbox, HTMLStencilElement {
    }
    var HTMLTestCheckboxElement: {
        prototype: HTMLTestCheckboxElement;
        new (): HTMLTestCheckboxElement;
    };
    interface HTMLElementTagNameMap {
        "test-checkbox": HTMLTestCheckboxElement;
    }
}
declare namespace LocalJSX {
    interface TestCheckbox {
        /**
          * The active checked state
         */
        "checked"?: boolean;
        /**
          * The default checked state
         */
        "defaultChecked"?: boolean;
        /**
          * Disabled state of checkbox
         */
        "disabled"?: boolean;
        /**
          * Name of the field
         */
        "label"?: string;
        /**
          * Label associated with the field
         */
        "name"?: string;
        /**
          * Emits boolean value of checked state
         */
        "onCheckedChange"?: (event: TestCheckboxCustomEvent<any>) => void;
        /**
          * underlying input value
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "test-checkbox": TestCheckbox;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "test-checkbox": LocalJSX.TestCheckbox & JSXBase.HTMLAttributes<HTMLTestCheckboxElement>;
        }
    }
}
